INSERT INTO candidates (name, email, title, company, experience_years, location, availability_status, match_percent, image_url, about)
VALUES 
('Alice Johnson', 'alice@example.com', 'Senior Frontend Engineer', 'TechCorp', 8, 'New York, NY', 'available', 95, 'https://randomuser.me/api/portraits/women/1.jpg', 'Experienced React developer with a passion for UI/UX.'),
('Bob Smith', 'bob@example.com', 'Full Stack Developer', 'StartUp Inc', 5, 'Remote', 'open_to_work', 88, 'https://randomuser.me/api/portraits/men/2.jpg', 'Versatile developer proficient in Node.js and React.'),
('Charlie Brown', 'charlie@example.com', 'Backend Engineer', 'BigBank', 10, 'London, UK', 'unavailable', 75, 'https://randomuser.me/api/portraits/men/3.jpg', 'Expert in scalable backend systems and microservices.'),
('Diana Prince', 'diana@example.com', 'Product Manager', 'Amazon', 7, 'Seattle, WA', 'available', 92, 'https://randomuser.me/api/portraits/women/4.jpg', 'Product leader with a technical background.'),
('Evan Wright', 'evan@example.com', 'DevOps Engineer', 'Google', 6, 'Mountain View, CA', 'available', 85, 'https://randomuser.me/api/portraits/men/5.jpg', 'Cloud infrastructure specialist.'),
('Fiona Gallagher', 'fiona@example.com', 'UX Designer', 'Adobe', 4, 'San Francisco, CA', 'open_to_work', 90, 'https://randomuser.me/api/portraits/women/6.jpg', 'Creative designer focused on accessibility.'),
('George Martin', 'george@example.com', 'Data Scientist', 'Netflix', 9, 'Los Gatos, CA', 'available', 89, 'https://randomuser.me/api/portraits/men/7.jpg', 'Machine learning expert specializing in recommendation systems.'),
('Hannah Lee', 'hannah@example.com', 'Mobile Developer', 'Apple', 5, 'Cupertino, CA', 'unavailable', 80, 'https://randomuser.me/api/portraits/women/8.jpg', 'iOS and Swift enthusiast.'),
('Ian Somerhalder', 'ian@example.com', 'Software Engineer', 'Meta', 3, 'Menlo Park, CA', 'available', 78, 'https://randomuser.me/api/portraits/men/9.jpg', 'Frontend specialist working on social media platforms.'),
('Julia Roberts', 'julia@example.com', 'QA Engineer', 'Microsoft', 6, 'Redmond, WA', 'available', 82, 'https://randomuser.me/api/portraits/women/10.jpg', 'Quality assurance professional with automation experience.'),
('Kevin Hart', 'kevin@example.com', 'System Architect', 'IBM', 12, 'Armonk, NY', 'open_to_work', 94, 'https://randomuser.me/api/portraits/men/11.jpg', 'Experienced architect designing enterprise solutions.'),
('Laura Croft', 'laura@example.com', 'Security Analyst', 'Cisco', 8, 'San Jose, CA', 'available', 87, 'https://randomuser.me/api/portraits/women/12.jpg', 'Cybersecurity expert with network security focus.'),
('Mike Ross', 'mike@example.com', 'Legal Counsel', 'Pearson Specter', 5, 'New York, NY', 'unavailable', 70, 'https://randomuser.me/api/portraits/men/13.jpg', 'Corporate lawyer provided for context in non-tech roles.'),
('Nina Dobrev', 'nina@example.com', 'Marketing Specialist', 'HubSpot', 4, 'Cambridge, MA', 'available', 85, 'https://randomuser.me/api/portraits/women/14.jpg', 'Digital marketing expert.'),
('Oscar Isaac', 'oscar@example.com', 'Cloud Architect', 'Oracle', 10, 'Austin, TX', 'available', 91, 'https://randomuser.me/api/portraits/men/15.jpg', 'Cloud infrastructure and database specialist.'),
('Paula Patton', 'paula@example.com', 'HR Manger', 'Workday', 7, 'Pleasanton, CA', 'open_to_work', 88, 'https://randomuser.me/api/portraits/women/16.jpg', 'Human resources professional with tech recruiting experience.'),
('Quentin Tarantino', 'quentin@example.com', 'Video Editor', 'Sony', 15, 'Los Angeles, CA', 'available', 80, 'https://randomuser.me/api/portraits/men/17.jpg', 'Creative video editor.'),
('Rachel Zane', 'rachel@example.com', 'Paralegal', 'Pearson Specter', 3, 'New York, NY', 'available', 72, 'https://randomuser.me/api/portraits/women/18.jpg', 'Aspiring lawyer.'),
('Steve Rogers', 'steve@example.com', 'Project Manager', 'SHIELD', 10, 'Washington, DC', 'unavailable', 96, 'https://randomuser.me/api/portraits/men/19.jpg', 'Leadership and project management.'),
('Tony Stark', 'tony@example.com', 'CTO', 'Stark Industries', 20, 'Malibu, CA', 'available', 99, 'https://randomuser.me/api/portraits/men/20.jpg', 'Visionary technologist and engineer.'),
('Ursula Andress', 'ursula@example.com', 'Database Admin', 'SAP', 8, 'Walldorf, Germany', 'open_to_work', 86, 'https://randomuser.me/api/portraits/women/21.jpg', 'Database administration and optimization.'),
('Vin Diesel', 'vin@example.com', 'Driver', 'Fast Co', 10, 'Los Angeles, CA', 'mock_data', 60, 'https://randomuser.me/api/portraits/men/22.jpg', 'Logistics and transportation.'),
('Wanda Maximoff', 'wanda@example.com', 'Frontend Developer', 'Westview Inc', 5, 'New Jersey', 'available', 93, 'https://randomuser.me/api/portraits/women/23.jpg', 'React and magic UI effects.'),
('Xander Cage', 'xander@example.com', 'Security specialist', 'NSA', 7, 'Washington, DC', 'available', 84, 'https://randomuser.me/api/portraits/men/24.jpg', 'Extreme security testing.'),
('Yara Shahidi', 'yara@example.com', 'Intern', 'Google', 1, 'Mountain View, CA', 'available', 75, 'https://randomuser.me/api/portraits/women/25.jpg', 'Aspiring software engineer.'),
('Zack Efron', 'zack@example.com', 'Sales Manager', 'Salesforce', 6, 'San Francisco, CA', 'open_to_work', 89, 'https://randomuser.me/api/portraits/men/26.jpg', 'Sales leadership.'),
('Aaron Paul', 'aaron@example.com', 'Chemist', 'Gray Matter', 4, 'Albuquerque, NM', 'unavailable', 65, 'https://randomuser.me/api/portraits/men/27.jpg', 'Process chemistry.'),
('Bryan Cranston', 'bryan@example.com', 'Teacher', 'J.P. Wynne', 20, 'Albuquerque, NM', 'unavailable', 70, 'https://randomuser.me/api/portraits/men/28.jpg', 'Chemistry teacher.'),
('Chloe Grace', 'chloe@example.com', 'Junior Dev', 'Spotify', 2, 'New York, NY', 'available', 81, 'https://randomuser.me/api/portraits/women/29.jpg', 'Backend development with Java.'),
('David Beckham', 'david@example.com', 'Sports Analyst', 'ESPN', 10, 'Bristol, CT', 'available', 76, 'https://randomuser.me/api/portraits/men/30.jpg', 'Sports data analysis.');
